"""Explicit degradation / provenance codes for API responses."""

from enum import Enum


class DegradationCode(str, Enum):
    OK = "OK"
    GEONAMES_PARTIAL = "GEONAMES_PARTIAL"
    WIKIPEDIA_UNAVAILABLE = "WIKIPEDIA_UNAVAILABLE"
    METEOSTAT_UNAVAILABLE = "METEOSTAT_UNAVAILABLE"
    ERA5_OPENMETEO_USED = "ERA5_OPENMETEO_USED"  # ERA5 grid via Open-Meteo climate API (CDS not used)
    CLIMATOLOGY_UNAVAILABLE = "CLIMATOLOGY_UNAVAILABLE"
    OPEN_METEO_HOURLY_TRUNCATED = "OPEN_METEO_HOURLY_TRUNCATED"
    DAILY_EXTENDED_FROM_OPEN_METEO = "DAILY_EXTENDED_FROM_OPEN_METEO"
    CURRENT_CONDITIONS_MISSING = "CURRENT_CONDITIONS_MISSING"
    NWS_AFD_UNAVAILABLE = "NWS_AFD_UNAVAILABLE"
    NWS_AFD_SKIPPED_NON_US = "NWS_AFD_SKIPPED_NON_US"
    CACHE_HIT_CONTEXT = "CACHE_HIT_CONTEXT"
    CACHE_HIT_METEOROLOGIST = "CACHE_HIT_METEOROLOGIST"
    CACHE_HIT_REPORT = "CACHE_HIT_REPORT"
